In [2]:
print("Hello World")

Hello World


In [12]:
import numpy as np
a = np.array([1, 2,3])
b = np.array([2,3,4])
a*b
a[:1]

array([1])

In [8]:
import numpy as np
a = np.array([[1.0, 2.0, 3.0], [1.0, 2, 3]], dtype=np.int8)
print(a)
print(a.ndim)
print(a.shape)
print(a.dtype)
a[1,:]

[[1 2 3]
 [1 2 3]]
2
(2, 3)
int8


array([1, 2, 3], dtype=int8)